return {
  -- 'heavenshell/vim-pydocstring',
  -- ft = { 'python' },
  -- -- Windowsではbuildをスキップ
  -- build = vim.fn.has 'win32' == 1 and nil or 'make install',
  -- config = function()
  --   -- docstring フォーマット: "google", "numpy", "pep257"
  --   vim.g.pydocstring_formatter = 'google'
  --
  --   -- Windowsでdoqのパスを自動検出
  --   if vim.fn.has 'win32' == 1 then
  --     -- 一般的なdoqのインストール場所を確認
  --     local possible_paths = {
  --       vim.fn.expand '~\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\doq.exe',
  --       vim.fn.expand '~\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\doq.exe',
  --       vim.fn.expand '~\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\doq.exe',
  --       vim.fn.expand '~\\AppData\\Roaming\\Python\\Python312\\Scripts\\doq.exe',
  --       vim.fn.expand '~\\AppData\\Roaming\\Python\\Python311\\Scripts\\doq.exe',
  --       'doq', -- PATHに通っている場合
  --     }
  --
  --     for _, path in ipairs(possible_paths) do
  --       if vim.fn.executable(path) == 1 then
  --         vim.g.pydocstring_doq_path = path
  --         vim.notify('vim-pydocstring: doq found at ' .. path, vim.log.levels.INFO)
  --         break
  --       end
  --     end
  --
  --     -- doqが見つからない場合はVim script版を使用
  --     if not vim.g.pydocstring_doq_path then
  --       vim.g.pydocstring_doq_path = ''
  --       vim.notify('vim-pydocstring: doq not found, using built-in template engine', vim.log.levels.WARN)
  --     end
  --   end
  -- end,
  -- keys = {
  --   { '<Leader>dc', '<Plug>(pydocstring)', ft = 'python', desc = 'Generate Python docstring' },
  -- },
}
